---
title: "Important Info"
date-modified: now
filters:
  - shinylive
---

This will be the home page for (most) of your retreat information!

## Important Notes
* If you arrive after 20:30 on the first night, please go straight to House \#1.
* Please remember linen, pillowcases \& towels are not provided.

## Schedule

### Friday
| Time | Activity |
| --- | --- |
| 18:00 | Arrive anytime after for check-in |
| 20:30 | Supper at House \#1 |

### Saturday
| Time | Activity |
| --- | --- |
| 09:00 | Breakfast |
| 10:00 | Activity \#1 |
| 12:30 | Lunch (Self-Organised) |
| 13:30 | Activity \#2 |
| 18:00 | Dinner at House \#1 |
| 19:00 | Worship \& Devotions |
| 21:00 | (Optional) Stargazing |

### Sunday
| Time | Activity |
| --- | --- |
| 08:30 | Breakfast |
| 09:30 | Checkout |
| 10:00 | Church at Phillip Island |
| 12:00 | Lunch \& Drive back to Melbourne |

## Menu

### Friday Supper
*Savory*

* Cheese board
* Corn Chips + Salsa + Guac
* Popcorn

*Sweet*

* Fruits
* Apple pie
* Banana bread
* Waffles

*Drinks*

* Tea
* Hot choc 

### Saturday Breakfast

* Bread
* Bacon \& Eggs
* Hashbrowns

### Saturday Dinner
*Entree*

* Turkish bread with Truffle Oil 🍄
* Pumpkin Soup with Cream
* Green Leaf Salad

*Main*

* Beef Ragu Pasta
* Chicken Wings

### Sunday Breakfast
* Pancakes
* Berries
* Maple Syrup \& Jam

## Activities
We will have most of Saturday to do stuff, some suggested activities include:

* Bowling
* Laser Tag
* Chocolate Factory
* A Maze'n Things
* Beach walk
* Day Hikes
* Boardgames

We will organise ourselves after breakfast.

## Pack List

**IMPORTANT:** This accommodation does not include: top & bottom sheets, pillowcases and bath towels. The accommodation does include doona/quilts with covers, pillows without covers, tea towels, hand towels and bathmats.

Essentials:

 - [ ] Bible
 - [ ] Towels
 - [ ] Pillowcase (or just your own pillow)
 - [ ] Linen for the bed OR sleeping bag
 - [ ] Clothes (It will be [cold](http://www.bom.gov.au/vic/forecasts/phillipisland.shtml))
 - [ ] Toiletries

Almost Essential:

- [ ] Your favourite plushie

Optional:

- [ ] Musical instruments
- [ ] Games
- [ ] Snacks